//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Term_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mobile
    {
        public int Id { get; set; }
        public string brand { get; set; }
        public string name { get; set; }
        public Nullable<int> price { get; set; }
        public string processor { get; set; }
        public string os { get; set; }
        public string display { get; set; }
        public string camera { get; set; }
        public string battery { get; set; }
        public string other { get; set; }
        public string image { get; set; }
    }
}
